language: node_js
# nodejs version
node_js: 
    - '14.15.1'

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install pnpm -g
  - pnpm add vuepress -D

# build
script:
  - cp -rf src/vue-awesome-countdown.vue docs/.vuepress/components/vac.vue
  - cp -rf src/vue-awesome-countdown.vue docs/.vuepress/components/countdown.vue
  - pnpm run docs:build

after_script:
  - cd vuepress
  - echo 'vac.js.org' > CNAME

  - git init
  - git add -A
  - git commit -m 'deploy'
  - git push --quiet --force "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master
env:
 global:
